"""Initial

Revision ID: 6bcef718f19b
Revises: 4e7e091c76e2
Create Date: 2023-10-13 15:00:23.754463

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel

from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '6bcef718f19b'
down_revision = '4e7e091c76e2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('solution',
    sa.Column('nodes', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('technologies', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('carriers', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('folder_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('solution')
    # ### end Alembic commands ###
