"""Added scenarios to solution

Revision ID: 834518d5d106
Revises: 6bcef718f19b
Create Date: 2023-10-16 11:19:14.469124

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel

from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '834518d5d106'
down_revision = '6bcef718f19b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('solution', sa.Column('scenarios', postgresql.ARRAY(sa.String()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('solution', 'scenarios')
    # ### end Alembic commands ###
